version: '2'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  api:
    image: vdm-api:latest
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017
    ports:
       - 8080:8080
  scraper:
    image: vdm-scraper:latest
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017